spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_essentials
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    schemas: ecom_essentials

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
#    show-sql: true
#  ?createDatabaseIfNotExist=true

#device:
#  api:
#    url: https://script:google:com/macros/s/AKfycbxNu27V2Y2LuKUIQMK8lX1y0joB6YmG6hUwB1fNeVbgzEh22TcDGrOak03Fk3uBHmz-/exec?route=device-list